# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updatetime', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(db_index=True, max_length=64)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('userpic', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tthread',
            name='users',
            field=models.ManyToManyField(to='messenger.TUser'),
        ),
        migrations.AddField(
            model_name='tmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.TThread'),
        ),
    ]
